# Generated by Django 5.0 on 2024-01-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="order",
            field=models.SmallIntegerField(default=0, verbose_name="Orden"),
        ),
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.TextField(verbose_name="Contenido"),
        ),
    ]
